#!/usr/bin/env node
// Packs the mnemonic illustrations in data/mnemonic-art/<block>.svg into
// js/lib/mnemonicArtData.js so the app (and the single-file preview) can use
// them without extra network requests. Checks each file first.
//
//   node tools/build-art.mjs

import { readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { MNEMONICS } from '../js/lib/mnemonics.js';

const here = dirname(fileURLToPath(import.meta.url));
const DIR = join(here, '..', 'data', 'mnemonic-art');
const OUT = join(here, '..', 'js', 'lib', 'mnemonicArtData.js');
const MAX_BYTES = 16000;

const problems = [];
const art = {};
for (const f of (await readdir(DIR)).filter((n) => n.endsWith('.svg')).sort((a, b) => parseInt(a, 10) - parseInt(b, 10))) {
  const block = Number(f.replace('.svg', ''));
  let svg = (await readFile(join(DIR, f), 'utf8')).trim();
  const bad = (msg) => problems.push(`${f}: ${msg}`);
  if (!(block in MNEMONICS)) { bad('not a street block number'); continue; }
  if (!svg.startsWith('<svg')) bad('must start with <svg (no XML prolog or comments before it)');
  if (!/viewBox="0 0 512 512"/.test(svg)) bad('needs viewBox="0 0 512 512"');
  if (/<script|<foreignObject|\son[a-z]+=|javascript:/i.test(svg)) bad('scripts, event handlers and foreignObject are not allowed');
  if (/(href|src)="(?!#)/i.test(svg)) bad('no external or embedded images/links (only #id references)');
  if (/<text|<tspan/i.test(svg)) bad('no text: the poster adds the name and number');
  if (!/xmlns="http:\/\/www.w3.org\/2000\/svg"/.test(svg)) bad('needs xmlns="http://www.w3.org/2000/svg"');
  // Make ids unique per file so several drawings can share a page.
  svg = svg.replace(/\bid="([^"]+)"/g, `id="m${block}-$1"`).replace(/url\(#([^)]+)\)/g, `url(#m${block}-$1)`).replace(/href="#([^"]+)"/g, `href="#m${block}-$1"`);
  svg = svg.replace(/>\s+</g, '><').replace(/\s{2,}/g, ' ');
  if (svg.length > MAX_BYTES) bad(`${svg.length} bytes; keep it under ${MAX_BYTES}`);
  art[block] = svg;
}

const missing = Object.keys(MNEMONICS).map(Number).filter((b) => !(b in art));
await writeFile(OUT, `// Generated by tools/build-art.mjs from data/mnemonic-art/*.svg. Do not edit by hand.\nexport const ART = ${JSON.stringify(art, null, 0).replace(/","/g, '",\n"')};\n`);
console.log(`packed ${Object.keys(art).length} illustrations into js/lib/mnemonicArtData.js; ${missing.length} streets still use the emoji poster`);
if (missing.length) console.log(`missing: ${missing.join(', ')}`);
if (problems.length) {
  console.error(`\n${problems.length} problem(s):\n${problems.join('\n')}`);
  process.exit(1);
}
